[workspace]
members = [
  "automata",
  "lalr",
  "lalrgen",
  "lalrgen-macro",
  "llex",
  "llex-macro",
  "pratt",
  "regexp",
  "regexp2",
]

[patch.crates-io]
tree = { git = "https://github.com/apasel422/tree" }
