[package]
name = "ast"
version = "0.1.0"
authors = ["Eric Zhao <21zhaoe@protonmail.com>"]
edition = "2018"

[dependencies]
lexer = { path = "../lexer" }

serde = { version = "1.0", features = ["derive", "rc"], optional = true }

[features]
serde-impl = ["serde"]
