[package]
name = "pratt"
version = "0.1.0"
authors = ["Eric Zhao <21zhaoe@protonmail.com>"]
license = "MIT"
edition = "2018"

[[bin]]
name = "pratt"
path = "src/main.rs"

[dependencies]
llex = { path = "../llex" }

thiserror = "1.0"
