[package]
name = "memalloc"
version = "0.1.0"
authors = ["Eric Zhao <21zhaoe@protonmail.com>"]
edition = "2018"

[lib]
name = "malloc"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
x86 = "0.36"
once_cell = "1.5.2"
spin = "0.7.1"

[dev-dependencies]
cfg-if = "1.0"
