[package]
name = "lalr"
version = "0.1.0"
authors = ["Eric Zhao <21zhaoe@protonmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
thiserror = "1.0"

[dev-dependencies]
llex = { path = "../llex" }
